[project]
name = "computer-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ninkuto", email = "catphu703@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pybullet>=3.2.7",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
]

[project.scripts]
computer-vision = "computer_vision:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
